name: Pelican site CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: bimbimprasetyoafif/pelican-simple@v1
      env:
        GH_PAGES_BRANCH: master
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
